-- schema.sql
CREATE DATABASE IF NOT EXISTS securechat;
USE securechat;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(255) NOT NULL UNIQUE,
  salt VARBINARY(32) NOT NULL,
  pwd_hash CHAR(64) NOT NULL
);
